-- AlterTable
ALTER TABLE "bookings" ALTER COLUMN "end_datetime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "start_datetime" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "room_promos" ALTER COLUMN "end_datetime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "start_datetime" SET DEFAULT CURRENT_TIMESTAMP;
